spring:
  application:
    name:eureka-server
server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  instance:
    metadata-map:
      instance-id: ${spring.application.name}:${spring.cloud.client.hostname}:${server.port}
      version: 1.0.0
      profile: ${spring.profiles.active}
      management.port: ${management.server.port:8761}