server:
  port: 8081

  profiles:
    active: dev

spring:
  application:
    name: product-service
  cloud:
    config:
      enabled: true
  config:
    import: optional:configserver:http://localhost:8889
  datasource:
    url: jdbc:postgresql://localhost:5432/product
    username: product
    password: product123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect



